// Rewrites catalog.js from Begad's product feed.
//
// catalog.js is only the snapshot the page paints first and falls back to;
// the page itself reloads the same feed on every visit (loadCatalog in
// app.js). Run by .github/workflows/sync-catalog.yml, or by hand:
//   node tools/sync-catalog.mjs
import { writeFile } from 'node:fs/promises';

const FEED = 'https://begad.ae/api/agent/prices?brand=vidvie&details=1';
const MIN_ITEMS = 20; // fewer than this means the feed is broken, not that the range shrank

const res = await fetch(FEED, { headers: { Accept: 'application/json' } });
if (!res.ok) throw new Error(`Begad feed answered HTTP ${res.status}`);
const data = await res.json();
if (!data.ok || !Array.isArray(data.items) || data.items.length < MIN_ITEMS) {
  throw new Error(`Begad feed looks wrong (${data.items ? data.items.length : 'no'} items); catalog.js left as it was`);
}

// Only what app.js reads (toProduct)
const items = data.items.map(item => ({
  id: item.id,
  sku: item.sku,
  name: item.name,
  category: item.category,
  url: item.url,
  thumb: item.thumb,
  price: {
    amount: item.price.amount,
    amount_with_tax: item.price.amount_with_tax,
    compare_at_amount: item.price.compare_at_amount
  },
  in_stock: item.in_stock
}));

const header = `// Snapshot of Begad's VIDVIE product list. Generated by tools/sync-catalog.mjs
// from ${FEED}
// Do not edit by hand: products, names, photos, prices and stock are managed
// on Begad.ae, and app.js replaces this list with the live one on every visit.
`;
await writeFile(new URL('../catalog.js', import.meta.url), `${header}const catalogProducts = ${JSON.stringify(items, null, 1)};\n`);
console.log(`catalog.js: ${items.length} products`);
